csharp:
  - "*/**/*.cs"

design:
  - "*/**/*.scss"
  - "*/**/*.css"

css:
  - "*/**/*.css"

scss:
  - "*/**/*.scss"

api:
  - "*/**/api/**/*"
  - "HeadHunter.HttpClients/Resource/**/*"
  - "HeadHunter.ResourceWebApplication/**/*"
  - "HeadHunter.HttpClients.Tests/Resource/**/*"
  - "HeadHunter.AuthorizationWebApplication/**/*"
  - "HeadHunter.ResourceWebApplication.ControllerTests/**/*"

javascript:
  - "*/**/*.js"

head hunter:
  - "*/**/api/headHunter/**/*"
  - "HeadHunter.HttpClients/HeadHunter/**/*"
  - "HeadHunter.HttpClients.Tests/HeadHunter/**/*"
  - "HeadHunter.ResourceWebApplication/Areas/HeadHunter/**/*"
  - "HeadHunter.ResourceWebApplication.ControllerTests/Areas/HeadHunter/**/*"

shell:
  - "*/**/*.sh"

typescript:
  - "*/**/*.ts"

vue:
  - "*/**/*.vue"

vuex:
  - "*/**/src/store/**/*"

vue-router:
  - "*/**/src/router/**/*"

mocha:
  - "*/**/tests/unit/**/*"

cypress:
  - "*/**/tests/e2e/**/*"

tests:
  - "*/**/tests/**/*"
  - "HeadHunter.HttpClients.Tests/**/*"
  - "HeadHunter.HttpClients.Common.Tests/**/*"
  - "HeadHunter.ResourceWebApplication.ControllerTests/**/*"

docker:
  - "*/**/Dockerfile"
  - "docker-compose.yml"

production:
  - "*/**/*.sh"
  - ".env.dist"
  - "nginx.conf"
  - "*/**/Dockerfile"
  - "docker-compose.yml"

frontend:
  - "*/**/*.js"
  - "*/**/*.ts"
  - "*/**/*.vue"
  - "*/**/*.css"
  - "*/**/*.scss"

backend:
  - "HeadHunter.ResourceWebApplication/**/"
  - "HeadHunter.AuthorizationWebApplication/**/"

github:
  - ".github/**/*"

npm:
  - "*/**/package.json"
  - "*/**/package-lock.json"

package:
  - "*/**/package.json"
  - "*/**/package-lock.json"

database:
  - "*/**/*.sql"
  - "HeadHunter.Database.MongoDB/**/*"
  - "HeadHunter.Database.PostgreSql/**/*"