global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "headhunter.prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["headhunter.prometheus:9090"]

  - job_name: "headhunter.node.exporter"
    static_configs:
    - targets: ["headhunter.node.exporter:9100"]