name: Docker Compose Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  vue-js-app-build:
    name: vue-js-app image build and push
    runs-on: ubuntu-latest
    env:
      PROJECT_SRC_DIR: head-hunter-vue-js-app
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/headhunter/vue-js-app:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f $PROJECT_SRC_DIR/Dockerfile --pull -t $DOCKER_IMAGE $PROJECT_SRC_DIR

      - name: Push docker image
        run: docker push $DOCKER_IMAGE

  authorization-web-app-build:
    name: authorization-web-app image build and push
    runs-on: ubuntu-latest
    env:
      PROJECT_SRC_DIR: HeadHunter.AuthorizationWebApplication
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/headhunter/authorization-web-app:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f $PROJECT_SRC_DIR/Dockerfile --pull -t $DOCKER_IMAGE .

      - name: Push docker image
        run: docker push $DOCKER_IMAGE

  resource-web-app-build:
    name: resource-web-app image build and push
    runs-on: ubuntu-latest
    env:
      PROJECT_SRC_DIR: HeadHunter.ResourceWebApplication
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/headhunter/resource-web-app:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f $PROJECT_SRC_DIR/Dockerfile --pull -t $DOCKER_IMAGE .

      - name: Push docker image
        run: docker push $DOCKER_IMAGE
      