name: Docker Compose Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  headhunter-vuejsapp-build:
    name: headhunter-vuejsapp image build and push
    runs-on: ubuntu-latest
    env:
      DOCKER_NAME: headhuntervuejsapp
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/headhunter/headhuntervuejsapp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move to frontend head-hunter-vue-js-app folder
        run: cd head-hunter-vue-js-app

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f Dockerfile --pull -t $DOCKER_IMAGE .

      - name: Push docker image
        run: docker push $DOCKER_IMAGE

  headhunter-authorizationwebapplication-build:
    name: headhunter-authorizationwebapplication image build and push
    runs-on: ubuntu-latest
    env:
      DOCKER_NAME: headhunterauthorizationwebapplication
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/headhunter/${DOCKER_NAME}:${GITHUB_REF##*/}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move to frontend HeadHunter.AuthorizationWebApplication folder
        run: cd HeadHunter.AuthorizationWebApplication

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f Dockerfile --pull -t $DOCKER_IMAGE .

      - name: Push docker image
        run: docker push $DOCKER_IMAGE

  headhunter-resourcewebapplication-build:
    name: headhunter-resourcewebapplication image build and push
    runs-on: ubuntu-latest
    env:
      DOCKER_NAME: headhunterresourcewebapplication
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/headhunter/${DOCKER_NAME}:${GITHUB_REF##*/}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move to frontend HeadHunter.ResourceWebApplication folder
        run: cd HeadHunter.ResourceWebApplication

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f Dockerfile --pull -t $DOCKER_IMAGE .

      - name: Push docker image
        run: docker push $DOCKER_IMAGE