name: Docker Stack Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  vue-js-app-build:
    name: vue-js-app image build, pull and push
    runs-on: ubuntu-latest
    env:
      PROJECT_SRC_DIR: head-hunter-vue-js-app
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/headhunter/vue-js-app:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f $PROJECT_SRC_DIR/Dockerfile --pull -t $DOCKER_IMAGE $PROJECT_SRC_DIR

      - name: Push docker image
        run: docker push $DOCKER_IMAGE

      - name: Deploy docker image
        uses: satak/webrequest-action@master
        with:
          url: http://lev4and.ru/portainer/api/webhooks/f63f2a61-9722-49f7-aa85-4a2445e3a373
          method: POST

  authorization-web-app-build:
    name: authorization-web-app image build, pull and push
    runs-on: ubuntu-latest
    env:
      PROJECT_SRC_DIR: HeadHunter.AuthorizationWebApplication
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/headhunter/authorization-web-app:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f $PROJECT_SRC_DIR/Dockerfile --pull -t $DOCKER_IMAGE .

      - name: Push docker image
        run: docker push $DOCKER_IMAGE

      - name: Deploy docker image
        uses: satak/webrequest-action@master
        with:
          url: http://lev4and.ru/portainer/api/webhooks/18bf5c6e-11c6-4751-b21d-ea140479560d
          method: POST

  resource-web-app-build:
    name: resource-web-app image build, pull and push
    runs-on: ubuntu-latest
    env:
      PROJECT_SRC_DIR: HeadHunter.ResourceWebApplication
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/headhunter/resource-web-app:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f $PROJECT_SRC_DIR/Dockerfile --pull -t $DOCKER_IMAGE .

      - name: Push docker image
        run: docker push $DOCKER_IMAGE
      
      - name: Deploy docker image
        uses: satak/webrequest-action@master
        with:
          url: http://lev4and.ru/portainer/api/webhooks/e14a9d3f-be0f-4fb5-9d7a-27900de9354e
          method: POST
  
  importer-console-app-build:
    name: importer-console-app image build, pull and push
    runs-on: ubuntu-latest
    env:
      PROJECT_SRC_DIR: HeadHunter.Importer.ConsoleApp
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/headhunter/importer-console-app:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f $PROJECT_SRC_DIR/Dockerfile --pull -t $DOCKER_IMAGE .

      - name: Push docker image
        run: docker push $DOCKER_IMAGE